title: Vishnu Menon
description: Machine Learning Engineer
baseurl: ""
url: "https://vishnus99.github.io"

author:
  name: Vishnu Menon

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
